const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const jwt=require('jsonwebtoken');
const {transition,validateLines,canSee}=require('../src/commerce/domain');const {authenticateToken}=require('../src/commerce/auth');const {createProviders}=require('../src/commerce/provider');const {loadConfig}=require('../src/commerce/config');

test('order state machine covers reservation, payment failure/retry, fulfillment, delivery, cancellation, and refund',()=>{
  assert.equal(transition('TAX_PENDING','tax_succeeded'),'PENDING_RESERVATION');assert.equal(transition('PENDING_RESERVATION','reserve'),'RESERVED');assert.equal(transition('RESERVED','request_payment'),'PAYMENT_PENDING');
  assert.equal(transition('PAYMENT_PENDING','payment_failed'),'PAYMENT_FAILED');assert.equal(transition('PAYMENT_FAILED','retry_payment'),'PAYMENT_PENDING');assert.equal(transition('PAYMENT_PENDING','payment_succeeded'),'PAID');
  assert.equal(transition('PAID','begin_fulfillment'),'FULFILLING');assert.equal(transition('FULFILLING','partial_fulfillment'),'PARTIALLY_FULFILLED');assert.equal(transition('PARTIALLY_FULFILLED','full_fulfillment'),'FULFILLED');
  assert.equal(transition('FULFILLED','dispatch'),'DELIVERY_PENDING');assert.equal(transition('DELIVERY_PENDING','dispatch_succeeded'),'IN_TRANSIT');assert.equal(transition('IN_TRANSIT','delivery_exception'),'DELIVERY_EXCEPTION');
  assert.equal(transition('PAID','cancel'),'REFUND_PENDING');assert.equal(transition('REFUND_PENDING','refund_succeeded'),'REFUNDED');assert.throws(()=>transition('COMPLETED','cancel'),/Cannot cancel/);
});
test('line validation uses integer quantities and rejects client price assumptions',()=>{assert.doesNotThrow(()=>validateLines([{inventoryId:'i',quantity:2}]));assert.throws(()=>validateLines([{inventoryId:'i',quantity:0}]),/positive/);});
test('role visibility scopes customers and merchants while operator can see all',()=>{const order={customer_subject:'c1',merchant_subject:'m1'};assert.equal(canSee({role:'customer',subject:'c1'},order),true);assert.equal(canSee({role:'customer',subject:'c2'},order),false);assert.equal(canSee({role:'merchant',subject:'m1'},order),true);assert.equal(canSee({role:'operator',subject:'o'},order),true);});
test('identity accepts only short RS256 tokens with tenant and commerce role',()=>{const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const config={publicKey:pair.publicKey.export({type:'spki',format:'pem'}),oidcIssuer:'https://id.test/',oidcAudience:'commerce'};const token=jwt.sign({tenant_id:crypto.randomUUID(),role:'merchant'},pair.privateKey,{algorithm:'RS256',subject:'m1',issuer:config.oidcIssuer,audience:config.oidcAudience,expiresIn:'5m'});assert.equal(authenticateToken(token,config).role,'merchant');const bad=jwt.sign({tenant_id:crypto.randomUUID(),role:'admin'},pair.privateKey,{algorithm:'RS256',subject:'a',issuer:config.oidcIssuer,audience:config.oidcAudience,expiresIn:'5m'});assert.throws(()=>authenticateToken(bad,config),/valid/);});
test('provider adapters send idempotency keys and classify transient failures',async()=>{let header;const providers=createProviders({tax:{baseUrl:'https://tax.test',token:'t'},payment:{baseUrl:'https://pay.test',token:'p'},delivery:{baseUrl:'https://delivery.test',token:'d'}},async(_url,options)=>{header=options.headers['idempotency-key'];return{ok:false,status:503};});await assert.rejects(providers.tax('calculate',{},'tax-key'),e=>e.retryable&&e.code==='TAX_503');assert.equal(header,'tax-key');});
test('production configuration fails closed on placeholders and insecure database mode',()=>{const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const env={NODE_ENV:'production',PORT:'5001',DATABASE_URL:'postgres://app:secret@db.internal/catering',DATABASE_SSL:'require',OIDC_ISSUER:'https://id.internal/',OIDC_AUDIENCE:'commerce',OIDC_LOGIN_URL:'https://id.internal/login',AUTH_PUBLIC_KEY_BASE64:Buffer.from(pair.publicKey.export({type:'spki',format:'pem'})).toString('base64'),WEBHOOK_SIGNING_SECRET:'s'.repeat(32),TAX_BASE_URL:'https://tax.internal',TAX_BEARER_TOKEN:'tax-secret',PAYMENT_BASE_URL:'https://pay.internal',PAYMENT_BEARER_TOKEN:'pay-secret',DELIVERY_BASE_URL:'https://delivery.internal',DELIVERY_BEARER_TOKEN:'delivery-secret'};assert.equal(loadConfig(env).production,true);assert.throws(()=>loadConfig({...env,DATABASE_SSL:'disable'}),/mandatory/);});
