const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const jwt=require('jsonwebtoken');const {Pool}=require('pg');
const {createCommerceApp,callbackSignature}=require('../src/commerce/app');
const databaseUrl=process.env.TEST_DATABASE_URL;
test('real commerce HTTP/PostgreSQL journey is idempotent, role scoped, retry safe, and auditable',{skip:!databaseUrl,timeout:30000},async t=>{
  const pool=new Pool({connectionString:databaseUrl});const migration=fs.readFileSync(path.join(__dirname,'..','db','migrations','001_governed_commerce.sql'),'utf8');await pool.query(migration);await pool.query(migration);await pool.query('TRUNCATE commerce_tenants RESTART IDENTITY CASCADE');
  const tenantA=(await pool.query(`INSERT INTO commerce_tenants(name)VALUES('Catering A')RETURNING id`)).rows[0].id;const tenantB=(await pool.query(`INSERT INTO commerce_tenants(name)VALUES('Catering B')RETURNING id`)).rows[0].id;
  const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const config={production:false,oidcIssuer:'https://id.test/',oidcAudience:'commerce',oidcLoginUrl:'https://id.test/login',publicKey:pair.publicKey.export({type:'spki',format:'pem'}),webhookSecret:'w'.repeat(32)};
  const providers={tax:async()=>({taxCents:250}),payment:async(operation,payload)=>{if(operation==='capture'&&payload.paymentMethodToken==='decline')throw Object.assign(new Error('declined'),{code:'PAYMENT_DECLINED',retryable:false});if(operation==='reconcile')return{transactions:[]};return{reference:`pay-${crypto.randomUUID()}`};},delivery:async()=>({reference:'delivery-1'})};
  const app=createCommerceApp({config,pool,providers});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{await new Promise(r=>server.close(r));await pool.end();});
  const make=(sub,role,tenant=tenantA)=>jwt.sign({tenant_id:tenant,role,email:`${sub}@test.invalid`,name:sub},pair.privateKey,{algorithm:'RS256',subject:sub,issuer:config.oidcIssuer,audience:config.oidcAudience,expiresIn:'5m'});const token={customer:make('customer-1','customer'),otherCustomer:make('customer-2','customer'),merchant:make('merchant-1','merchant'),operator:make('operator-1','operator'),otherTenant:make('operator-b','operator',tenantB)};
  async function req(url,auth,options={}){const headers={...(options.body?{'content-type':'application/json'}:{}),...(auth?{authorization:`Bearer ${auth}`}:{ }),...(options.headers||{})};const response=await fetch(base+url,{...options,headers,body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});const text=await response.text();let data;try{data=text?JSON.parse(text):{};}catch{data=text;}return{status:response.status,data};}
  assert.equal((await req('/api/health')).status,200);assert.equal((await req('/api/commerce/orders')).status,401);
  const stock=await req('/api/commerce/inventory',token.merchant,{method:'POST',body:{sku:'DINNER-001',name:'Dinner service',availableQuantity:5,unitPriceCents:2000}});assert.equal(stock.status,201);const inventoryId=stock.data.inventory.id;
  const createBody={merchantSubject:'merchant-1',idempotencyKey:'checkout-1',postalCode:'10001',lines:[{inventoryId,quantity:3}]};const created=await req('/api/commerce/orders',token.customer,{method:'POST',body:createBody});assert.equal(created.status,201);const orderId=created.data.order.id;assert.equal((await req('/api/commerce/orders',token.customer,{method:'POST',body:createBody})).data.order.id,orderId);
  assert.equal((await req(`/api/commerce/orders/${orderId}`,token.otherCustomer)).status,403);assert.equal((await req('/api/commerce/orders',token.otherTenant)).data.orders.length,0);
  async function jobs(){return(await req('/api/commerce/jobs',token.operator)).data.jobs;}async function execute(provider,operation,order=orderId){const job=(await jobs()).find(j=>j.provider===provider&&j.operation===operation&&j.order_id===order&&j.status==='queued');assert.ok(job,`missing ${provider}/${operation}`);return req(`/api/commerce/jobs/${job.id}/execute`,token.operator,{method:'POST'});}
  assert.equal((await execute('tax','calculate')).status,200);assert.equal((await req(`/api/commerce/orders/${orderId}/reserve`,token.merchant,{method:'POST'})).data.order.state,'RESERVED');
  const second=await req('/api/commerce/orders',token.customer,{method:'POST',body:{...createBody,idempotencyKey:'checkout-oversell'}});await execute('tax','calculate',second.data.order.id);assert.equal((await req(`/api/commerce/orders/${second.data.order.id}/reserve`,token.merchant,{method:'POST'})).status,409);const inventoryAfter=(await req('/api/commerce/inventory',token.merchant)).data.inventory[0];assert.equal(inventoryAfter.available_quantity,2);assert.equal(inventoryAfter.reserved_quantity,3);
  const pay=await req(`/api/commerce/orders/${orderId}/payment`,token.customer,{method:'POST',body:{idempotencyKey:'capture-decline',paymentMethodToken:'decline'}});assert.equal(pay.status,202);const declined=await req(`/api/commerce/jobs/${pay.data.job.id}/execute`,token.operator,{method:'POST'});assert.equal(declined.status,502);assert.equal(declined.data.job.status,'dead-letter');assert.equal((await req(`/api/commerce/orders/${orderId}`,token.customer)).data.order.state,'PAYMENT_FAILED');
  const retry=await req(`/api/commerce/orders/${orderId}/payment`,token.customer,{method:'POST',body:{idempotencyKey:'capture-good',paymentMethodToken:'tok_good'}});assert.equal((await req(`/api/commerce/jobs/${retry.data.job.id}/execute`,token.operator,{method:'POST'})).status,200);let order=(await req(`/api/commerce/orders/${orderId}`,token.customer)).data.order;assert.equal(order.state,'PAID');
  const line=order.lines[0];assert.equal((await req(`/api/commerce/orders/${orderId}/fulfill`,token.merchant,{method:'POST',body:{lineId:line.id,quantity:1,idempotencyKey:'fulfill-1'}})).data.order.state,'PARTIALLY_FULFILLED');assert.equal((await req(`/api/commerce/orders/${orderId}/fulfill`,token.merchant,{method:'POST',body:{lineId:line.id,quantity:1,idempotencyKey:'fulfill-1'}})).data.order.state,'PARTIALLY_FULFILLED');assert.equal((await req(`/api/commerce/orders/${orderId}/fulfill`,token.merchant,{method:'POST',body:{lineId:line.id,quantity:2,idempotencyKey:'fulfill-2'}})).data.order.state,'FULFILLED');
  const dispatch=await req(`/api/commerce/orders/${orderId}/dispatch`,token.merchant,{method:'POST',body:{idempotencyKey:'dispatch-1',address:'1 Main St',window:'12:00-13:00'}});assert.equal((await req(`/api/commerce/jobs/${dispatch.data.job.id}/execute`,token.operator,{method:'POST'})).status,200);assert.equal((await req(`/api/commerce/orders/${orderId}/exception`,token.merchant,{method:'POST',body:{code:'VEHICLE_DELAY',details:'Flat tire'}})).data.order.state,'DELIVERY_EXCEPTION');assert.equal((await req(`/api/commerce/orders/${orderId}/recover`,token.merchant,{method:'POST',body:{plan:'Replacement vehicle'}})).data.order.state,'IN_TRANSIT');
  const callbackBody=JSON.stringify({event:'delivery_completed',orderId});const callbackHeaders={'content-type':'application/json','x-tenant-id':tenantA,'x-delivery-id':'delivery-event-1','x-signature':callbackSignature(callbackBody,config.webhookSecret)};assert.equal((await req('/api/webhooks/delivery',null,{method:'POST',headers:callbackHeaders,body:callbackBody})).status,202);assert.equal((await req('/api/webhooks/delivery',null,{method:'POST',headers:callbackHeaders,body:callbackBody})).data.duplicate,true);assert.equal((await req(`/api/commerce/orders/${orderId}`,token.customer)).data.order.state,'COMPLETED');
  const refundable=await req('/api/commerce/orders',token.customer,{method:'POST',body:{merchantSubject:'merchant-1',idempotencyKey:'checkout-refund',postalCode:'10001',lines:[{inventoryId,quantity:1}]}});const refundOrder=refundable.data.order.id;await execute('tax','calculate',refundOrder);await req(`/api/commerce/orders/${refundOrder}/reserve`,token.merchant,{method:'POST'});const capture=await req(`/api/commerce/orders/${refundOrder}/payment`,token.customer,{method:'POST',body:{idempotencyKey:'capture-refund',paymentMethodToken:'tok_good'}});await req(`/api/commerce/jobs/${capture.data.job.id}/execute`,token.operator,{method:'POST'});const cancelled=await req(`/api/commerce/orders/${refundOrder}/cancel`,token.customer,{method:'POST',body:{reason:'Event cancelled',idempotencyKey:'refund-1'}});assert.equal(cancelled.data.order.state,'REFUND_PENDING');assert.equal((await req(`/api/commerce/jobs/${cancelled.data.job.id}/execute`,token.operator,{method:'POST'})).status,200);assert.equal((await req(`/api/commerce/orders/${refundOrder}`,token.customer)).data.order.state,'REFUNDED');
  const reconciliation=await req('/api/commerce/reconciliation',token.operator,{method:'POST',body:{from:'2026-07-01',to:'2026-07-31',idempotencyKey:'reconcile-1'}});assert.equal(reconciliation.status,201);assert.equal(reconciliation.data.run.status,'exceptions');assert.ok(Number(reconciliation.data.run.exception_count)>=2);
  await assert.rejects(async()=>pool.query(`UPDATE commerce_audit_events SET action='tamper' WHERE tenant_id=$1`,[tenantA]),/append-only/);assert.ok(Number((await pool.query(`SELECT count(*) FROM commerce_audit_events WHERE tenant_id=$1`,[tenantA])).rows[0].count)>=15);
});
