import{useCallback,useEffect,useState}from'react';import api from'../utils/api';import{useAuth}from'../context/AuthContext';import{RefreshCw,ShieldAlert}from'lucide-react';
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);
export default function CommerceOperations(){const{user}=useAuth();const[orders,setOrders]=useState([]),[inventory,setInventory]=useState([]),[jobs,setJobs]=useState([]),[error,setError]=useState('');const[merchant,setMerchant]=useState(''),[item,setItem]=useState(''),[quantity,setQuantity]=useState(1);
const load=useCallback(async()=>{setError('');try{const[o,i]=await Promise.all([api.get('/commerce/orders'),api.get('/commerce/inventory')]);setOrders(o.data.orders);setInventory(i.data.inventory);if(user.role==='operator')setJobs((await api.get('/commerce/jobs')).data.jobs);}catch(e){setError(e.response?.data?.error||e.message)}},[user.role]);useEffect(()=>{load()},[load]);
async function act(path,body={}){try{await api.post(path,body);await load()}catch(e){setError(e.response?.data?.error||e.message)}}
async function createOrder(e){e.preventDefault();await act('/commerce/orders',{merchantSubject:merchant,idempotencyKey:crypto.randomUUID(),postalCode:'10001',lines:[{inventoryId:item,quantity:Number(quantity)}]});}
async function upsertInventory(e){e.preventDefault();const f=new FormData(e.target);await act('/commerce/inventory',{sku:f.get('sku'),name:f.get('name'),availableQuantity:Number(f.get('quantity')),unitPriceCents:Number(f.get('price'))});e.target.reset();}
return <div className="space-y-6"><header className="flex justify-between items-start"><div><p className="text-xs font-bold uppercase tracking-widest text-indigo-600">Transactional order control</p><h1 className="text-3xl font-bold">Commerce operations</h1><p className="text-gray-600">Provider-backed tax, payment, refund, delivery, inventory reservation, and immutable history.</p></div><button className="btn btn-secondary flex gap-2" onClick={load}><RefreshCw size={17}/>Refresh</button></header>{error&&<div className="bg-red-50 text-red-700 p-4 rounded-lg flex gap-2"><ShieldAlert/>{error}</div>}
{user.role==='merchant'&&<form className="card grid grid-cols-4 gap-3" onSubmit={upsertInventory}><h2 className="col-span-4 font-semibold">Publish authoritative inventory</h2><input className="input" name="sku" placeholder="SKU" required/><input className="input" name="name" placeholder="Service/item" required/><input className="input" name="quantity" type="number" min="0" placeholder="Available" required/><input className="input" name="price" type="number" min="0" placeholder="Unit price cents" required/><button className="btn btn-primary col-span-4">Save inventory</button></form>}
{user.role==='customer'&&<form className="card grid grid-cols-3 gap-3" onSubmit={createOrder}><h2 className="col-span-3 font-semibold">Create idempotent order</h2><input className="input" value={merchant} onChange={e=>setMerchant(e.target.value)} placeholder="Merchant subject" required/><select className="select" value={item} onChange={e=>setItem(e.target.value)} required><option value="">Inventory item</option>{inventory.map(i=><option key={i.id} value={i.id}>{i.name} · {money(i.unit_price_cents)} · {i.available_quantity} available</option>)}</select><input className="input" type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button className="btn btn-primary col-span-3">Create and calculate tax</button></form>}
<section className="space-y-3"><h2 className="text-xl font-semibold">Role-scoped orders</h2>{orders.map(o=><article className="card" key={o.id}><div className="flex justify-between"><div><strong>{o.order_number}</strong><p className="text-sm text-gray-500">Customer {o.customer_subject} · Merchant {o.merchant_subject}</p></div><span className="badge badge-info">{o.state}</span></div><div className="mt-3 flex gap-6 text-sm"><span>Subtotal {money(o.subtotal_cents)}</span><span>Tax {money(o.tax_cents)}</span><span className="font-semibold">Total {money(o.total_cents)}</span><span>Version {o.version}</span></div><div className="mt-4 flex gap-2 flex-wrap">
{['PENDING_RESERVATION'].includes(o.state)&&user.role!=='customer'&&<button className="btn btn-primary" onClick={()=>act(`/commerce/orders/${o.id}/reserve`)}>Reserve inventory</button>}{['RESERVED','PAYMENT_FAILED'].includes(o.state)&&user.role!=='merchant'&&<button className="btn btn-primary" onClick={()=>act(`/commerce/orders/${o.id}/payment`,{idempotencyKey:crypto.randomUUID(),paymentMethodToken:'provider-token-from-checkout'})}>Pay / retry</button>}{['PAID','FULFILLING','PARTIALLY_FULFILLED'].includes(o.state)&&user.role!=='customer'&&<button className="btn btn-success" onClick={()=>{const lineId=prompt('Order line UUID');const qty=Number(prompt('Quantity fulfilled'));if(lineId&&qty)act(`/commerce/orders/${o.id}/fulfill`,{lineId,quantity:qty,idempotencyKey:crypto.randomUUID()})}}>Record fulfillment</button>}{o.state==='FULFILLED'&&user.role!=='customer'&&<button className="btn btn-primary" onClick={()=>act(`/commerce/orders/${o.id}/dispatch`,{idempotencyKey:crypto.randomUUID(),address:prompt('Delivery address'),window:prompt('Delivery window')})}>Dispatch</button>}{o.state==='DELIVERY_EXCEPTION'&&user.role!=='customer'&&<button className="btn btn-secondary" onClick={()=>act(`/commerce/orders/${o.id}/recover`,{plan:prompt('Recovery plan')})}>Recover exception</button>}{['TAX_PENDING','PENDING_RESERVATION','RESERVED','PAYMENT_FAILED','PAID','FULFILLING','PARTIALLY_FULFILLED','FULFILLED','DELIVERY_EXCEPTION'].includes(o.state)&&user.role!=='merchant'&&<button className="btn btn-danger" onClick={()=>act(`/commerce/orders/${o.id}/cancel`,{reason:prompt('Cancellation reason'),idempotencyKey:crypto.randomUUID()})}>Cancel / refund</button>}
{o.lines?.map(line=><p className="mt-2 text-xs font-mono text-gray-500" key={line.id}>Line {line.id} · ordered {line.quantity} · fulfilled {line.fulfilled_quantity}</p>)}</div></article>)}</section>
{user.role==='operator'&&<section className="card"><div className="flex justify-between"><h2 className="font-semibold">Provider queue and reconciliation</h2><button className="btn btn-secondary" onClick={()=>act('/commerce/reconciliation',{from:new Date(Date.now()-86400000).toISOString(),to:new Date().toISOString(),idempotencyKey:crypto.randomUUID()})}>Reconcile payments</button></div><div className="mt-4 space-y-2">{jobs.map(j=><div className="flex justify-between border rounded p-3" key={j.id}><span>{j.provider} / {j.operation} · {j.status} · attempts {j.attempts}</span>{['queued','retryable'].includes(j.status)&&<button className="btn btn-primary" onClick={()=>act(`/commerce/jobs/${j.id}/execute`)}>Execute</button>}</div>)}</div></section>}</div>}
